name: "install-cspdk"
description: "Installs Cryptographic Service Provider Development Kit headers and libraries"

runs:
  using: "composite"
  steps:
    - name: "cd"
      shell: cmd
      run: |
        cd
    - name: "pwd"
      shell: cmd
      run: |
        dir
    - name: "Copy CSPDK files into original installation directory"
      shell: cmd
      run: |
        xcopy CSPKD "C:\Program Files\Windows Kits\10\Cryptographic Provider Development Kit" /I /E
